server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /published-blogs {
        root /usr/share/nginx/html;
        try_files /published-blogs.html =404;
    }
}
